### ISSUE TITLE
Migrate lifetimes to middleware

### ISSUE THREAD

**Issue by annybs** [edge/databank#17]
In extension to #16 we should look at migrating the lifetime functionality to middleware.

Being able to leave it out of a Databank configuration would open up some new avenues, e.g. adding drivers for external cache backends like Redis and letting them deal with data lifetimes in their own way.

**Comment by mingard** [comment]
From slack:

"I think redis is overkill. An entire storage service just to handle removing old entries, and we’d still have to specifically define the expiry with redis. It’s also possible that the key will be renewed by gateway and then we’d have to manage that with redis to stop it expiring"

**Comment by annybs** [comment]
Agreed after some reflection. This work isn't really necessary - Databank serves a specific purpose, and we can use a different storage solution if we ever need to work without lifetimes.
